#!/usr/bin/env bash

# checks to see if symbolic links for
# personal dotfiles exist in $HOME
# creates symbolic links from dotfiles in .zbin if not

cd $HOME/.zbin

for f in .bashrc .bash_profile .vimrc .gvimrc
do
    if [[ -L $HOME/${f} ]]
    then echo "${f} exists"
    else
	echo "${f} will be created" &&
	    ln -s $HOME/.zbin/${f} $HOME/${f}
    fi
done

